version: "3"

services:
  discord-musicbot:
    build: .
    image: discord-musicbot:latest
    container_name: discord-musicbot
    restart: unless-stopped
    networks:
      - lavalink-net
    depends_on:
      - lavalink
    volumes:
      - ./config.js:/usr/src/app/config.js:ro

  lavalink:
    image: fredboat/lavalink:439f122
    container_name: music-lavalink
    hostname: lavalink
    restart: unless-stopped
    networks:
      - lavalink-net
    volumes:
      - ./docker/application.yml:/opt/Lavalink/application.yml:ro

networks:
  lavalink-net:
